---
title: "Pacific Island to National standards comparisons"
author: "Todd-Brown, Katherine"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# (380) WINDBREAK-SHELTERBELT ESTABLISHMENT AND RENOVATION


Overall references to snow are removed from Pacific Island specifications, burning is not allowed in Pacific Islands, species are specifications are difference, and restoration is explicitly named in Pacific islands.

```{sh eval=FALSE}
diff data_lvl02/380_Windbreak_Shelterbelt_Establishment_NHCP_CPS_2021.yml data_lvl02/380_Windbreak_Shelterbelt_Establishment_PIA_CPS_2022.yml > data_lvl03/380_compare.log
```

```{r}
#read_yaml('data_lvl02/380_Windbreak_Shelterbelt_Establishment_NHCP_CPS_2021.yml')
#read_yaml('data_lvl02/380_Windbreak_Shelterbelt_Establishment_PIA_CPS_2022.yml')
```

# 612

```{sh eval=FALSE}
diff data_lvl02/612_Tree_Shrub_Establishment_NHCP_CPS_2022.yml data_lvl02/612_Tree_Shrub_Establishment_PI_CPS_2017.yml > data_lvl03/612_compare.log
```

# 336

```{sh eval=FALSE}
diff data_lvl02/336_Soil_Carbon_Amendment_PI_CPS.yml data_lvl02/336_Soil_Carbon_Amendment_NHCP_CPS_2022.yml > data_lvl03/336_compare.log
```

# 484

```{sh eval=FALSE}
diff data_lvl02/484_Mulching_PI_CPS_2022.yml data_lvl02/484_Mulching_NHCP_CPS_2017.yml > data_lvl03/484_compare.log
```

# 327

```{sh eval=FALSE}
diff data_lvl02/327_Conservation_Cover_PI_CPS_2016.yaml data_lvl02/327_Conservation_Cover_NHCP_CPS_2014.yml > data_lvl03/327_compare.log
```

## CSP 380 Windbreak

```{sh eval=FALSE}
diff data_lvl02/380_Windbreak_Shelterbelt_Establishment_NHCP_CPS_2021.yaml data_lvl02/380_Windbreak_Shelterbelt_Establishment_PIA_CPS_2022.yaml > data_lvl03/380_compare.log
```

```{r}
NHCP380 <- read_yaml('data_lvl02/380_Windbreak_Shelterbelt_Establishment_NHCP_CPS_2021.yaml')
PIA380 <- read_yaml('data_lvl02/380_Windbreak_Shelterbelt_Establishment_PIA_CPS_2022.yaml')

```


## CSP 379 Forest Farming

```{sh eval=FALSE}
diff data_lvl02/379_Forest_Farming_NHCP_CPS_2020.yaml data_lvl02/379_Forest_Farming_PIA_CPS_2023.yaml > data_lvl03/379_compare.log
```

```{r}
PIA380 <- read_yaml('data_lvl02/380_Windbreak_Shelterbelt_Establishment_PIA_CPS_2022.yaml')

NHCP380 <- read_yaml('data_lvl02/380_Windbreak_Shelterbelt_Establishment_NHCP_CPS_2021.yaml')

#base::intersect(PIA380, NHCP380)
```

## CSP 612 Tree Shrub Establishment

```{sh eval=FALSE}
diff data_lvl02/612_Tree_Shrub_Establishment_NHCP_CPS_2022.yaml data_lvl02/612_Tree_Shrub_Establishment_PI_CPS_2017.yaml > data_lvl03/612_compare.log
```

```{r}
PIA612 <- read_yaml('data_lvl02/612_Tree_Shrub_Establishment_PI_CPS_2017.yaml')

NHCP612 <- read_yaml('data_lvl02/612_Tree_Shrub_Establishment_NHCP_CPS_2022.yaml')

```